apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-5fee
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-5fee@sha256:955e410ec1d46d3eda9a588b089594dc53b97fcb5a5cb3a1efd0df5f50a52be1
        name: my-nodejs
        resources: {}
status: {}
